### ISSUE TITLE
No full support by Atom?

### ISSUE THREAD

**Issue by cobalamin** [i-tu/Hasklig#7] opened 2014-11-16 22:35 UTC
I tried setting up this font in Atom, and after I disabled hardware acceleration and added `body { text-rendering: optimizeLegibility; ` to my css configuration, it seemed to work, but the cursor shows up in the wrong place (and it gets worse the more ligatures you have in a line). The cursor shown here is actually at the end of the line:

![screenshot from 2014-11-16 23 32 11](https://cloud.githubusercontent.com/assets/669103/5063486/d478f1de-6de8-11e4-9871-5874663bb754.png)

I just want to clarify if Atom has been able to use the font with full support before in a different config/version/system. I'm using the current version `0.146.0` on Ubuntu 14.04.

**Comment by ai** [comment] 2015-01-09 12:06
@kennethormandy `font-feature-settings` do not helps (string is ends by `)`):

![](http://i.imgur.com/JWVbvEa.png)

**Comment by ai** [comment] 2015-01-09 12:07
Same issue: #3821

**Comment by MethodGrab** [comment] 2015-05-21 08:09
It's an Atom issue, see https://github.com/atom/atom/issues/3821 & https://github.com/atom/atom/issues/6055.

**Comment by evanrelf** [comment] 2015-07-15 19:31
Atom is still listed in the README under editors that do support ligatures, but it doesn't (yet)... it should be moved under the "No support" heading, with a link to any issues from [atom/atom](https://github.com/atom/atom) regarding ligatures.

**Comment by i-tu** [comment] 2015-08-04 07:13
I agree with @evanrelf, will change README accordingly.

**Comment by steelbrain** [comment] 2015-10-13 21:44
I can confirm that since the latest atom release (currently beta), ligatures are fully supported!

**Comment by MethodGrab** [comment] 2015-10-30 09:57
:zap: Atom 1.1.0 has landed with liga support http://blog.atom.io/2015/10/29/atom-1-1-is-out.html! :zap:

**Comment by benjamin-rood** [comment] 2015-12-29 22:52
How can we help to (i.e. contribute to) extend the support for Hasklig ligatures into other source code formats in Atom?

For example, Fira Code mostly works in the Go code I write every day, but Hasklig does not.

**Comment by i-tu** [comment] 2015-12-31 17:20
@benjamin-rood : How exactly? Can you provide a code sample? I will close this issue, consider starting a new one.

**Closed by i-tu** 2015-12-31 17:20 UTC
Labels: application support
