### ISSUE TITLE
Bold font mid-line causes misalignment

### ISSUE THREAD

**Issue by SeinopSys** [i-tu/Hasklig#93] opened 2017-08-04 00:57 UTC
I use highlighting settings in my IDE (PhpStorm 2017.1.4) that makes certain parts of the code bold, and when I switch to this font the bold characters cause misalignment in the rest of the text. Here's an illustration of how this looks:
> ![9icbi4xcr9 1](https://user-images.githubusercontent.com/3200580/28949721-f66e1a88-78be-11e7-8d88-a0aea8199800.png)

Notice how the `y` in the second like is hanging into the space the `-` in the line above is occupying. Another example with a longer bold section:
>![fhd8upqy3m 1](https://user-images.githubusercontent.com/3200580/28949847-c6bf081e-78bf-11e7-93c0-4445fc43afae.png)

The text in the bottom is actually 1 character shorter but it's rendered even longer than the line above it.

This seems to happen only with the weight variants Hasklig Medium, Hasklig Light, Hasklig ExtraLight and Hasklig Black but not Hasklig Semibold or the one simply called Hasklig in the editor's font selection drop-down.

**Comment by i-tu** [comment] 2017-08-08 07:14
Thanks for your report. This is *probably* a problem with PhpStorm, as I'm unable to reproduce this problem.
 
<img width="727" alt="screen shot 2017-08-08 at 10 09 56" src="https://user-images.githubusercontent.com/2201932/29060283-c86e8f4e-7c21-11e7-9757-f04a84cff18b.png">

Could you please bring this up with the people working on PhpStorm? I'm closing this for the moment, until there's some compelling evidence that the problem lies in Hasklig.

**Closed by i-tu** 2017-08-08 07:14 UTC
